pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=ci
    actions:
      merge:
        method: merge
  - name: Automatic merge for Scala Steward
    conditions:
      - author=scala-steward
      - check-success=ci
    actions:
      merge:
        method: merge
